version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: vincent290587/armubuntu:latest
    steps:
      - checkout
      - run: sudo apt-get update ; sudo apt-get install curl
      - run:
          name: Creating Build Files
          command: 'cd TDD && cmake ..'
      - run:
          name: Creating Binary Files
          command: 'cd TDD && make'
      - run:
          name: TDD APP test
          command: 'cd TDD && make cov_xml'
      - codecov/upload:
          file: TDD/cov.xml
