version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: vincent290587/armubuntu:latest
    steps:
      - checkout
      - run: sudo apt-get update ; sudo apt-get -qq -y install curl lcov python ; export CODECOV_TOKEN="7de30547-11e1-430e-a04c-278a99efad75"
      - run:
          name: Creating Build Files
          command: 'cd TDD && cmake ..'
      - run:
          name: Creating Binary Files and running
          command: 'cd TDD && make && make cov_xml'
      - codecov/upload:
          file: TDD/cov_xml.xml
