version: 2

orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: vincent290587/armubuntu:latest
    steps:
      - checkout
      - run:
          name: Creating Build Files
          command: 'cd TDD && cmake ..'
      - run:
          name: Creating Binary Files
          command: 'cd TDD && make'
      - run:
          name: TDD APP test
          command: 'cd TDD && make cov_xml'
      - codecov/upload:
          file: {{ TDD/cov.xml }}
